Repository milieuinfo/webcomponenten-vl-ui, pull requests merged in 2020-07, with the labels that each got.

#51 Update dependency jsdoc to v3.6.4
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#52 Update dependency vl-ui-cookie-consent to v4.0.6
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#53 Update dependency vl-ui-core to v5.6.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#54 Update dependency vl-ui-pill to v4.0.4
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#55 Update dependency vl-ui-search to v1.1.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#56 Update dependency vl-ui-select to v4.1.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#57 Update dependency vl-ui-body to v1.0.3
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#58 Update dependency vl-ui-content-header to v3.0.4
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#60 Update dependency jsdoc to v3.6.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#62 Release problemen opgelost
  bamboo-specs/bamboo.yml
Labels: bug

#63 Nieuwe componenten toegevoegd aan bundled dependencies voor de demo pagina
  package.json
Labels: chore

#64 Update dependency vl-ui-input-field to v3.2.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#65 Update dependency vl-ui-proza-message to v1.1.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#66 Update dependency vl-ui-form-validation to v3.2.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#67 Update dependency vl-ui-input-field to v3.2.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#68 Update dependency vl-ui-progress-bar to v1.1.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate
