Repository milieuinfo/webcomponenten-vl-ui, pull requests merged in 2020-09, with the labels that each got.

#81 Update webcomponenten-vl-ui-bom dependency
  package-lock.json
  package.json
Labels: chore

#82 Update dependencies en introductie vl-ui-breadcrumb en vl-ui-video-player
  package-lock.json
  package.json
Labels: enhancement

#84 Update dependency jsdoc to v3.6.6
  package-lock.json
  package.json
Labels: chore, dependencies, renovate
